version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports: 
      - "5432:5432"
    volumes: 
      - postgresdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
      - PGADMIN_LISTEN_PORT=
    ports:
      - " : "
    volumes: 
      - pgadmindata:/var/lib/pgadmin
    depends_on: 
      - postgres

volumes:
  postgresdata:
  pgadmindata: