version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes: 
      - postgresdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes: 
      - pgadmindata:/var/lib/pgadmin
    depends_on: 
      - postgres

volumes:
  postgresdata:
  pgadmindata: