name: Build Code

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs: 

  analyze-code:
    runs-on:  ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Clean dependencies
        run:  go mod tidy

      - name: Verify dependencies
        run:  go mod verify

      - name: Vet code
        run:  go vet ./...

      - name: Install static-check
        run:  go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run static-check
        run:  staticcheck ./...

      - name: Install golint
        run:  go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Build code
        run:  go build -v ./...
